version: 2
jobs:
  build:
    docker:
      # As of right now these both use jessie as a base.
      # :fingers_crossed: they won't change
      - image: circleci/golang:1.9
    working_directory: /go/src/disconnect24.xyz/disguise-api
    steps:
      - checkout
      # Download our go deps and test.
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      # Looks like it worked, awesome! ^^
      - run:
          name: Install Cloud SDK + deploy if master
          command: |
            if [ "$(git rev-parse --abbrev-ref HEAD)" "==" "master" ] || [ -z $CIRCLE_PR_USERNAME ]; then
              # Time to push!
              curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=$HOME --disable-prompts
              echo "$CLIENT_SECRET" | base64 --decode > ${HOME}/client-secret.json
              $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file $HOME/client-secret.json
              $HOME/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT
              $HOME/google-cloud-sdk/bin/gcloud -q app deploy app.yaml --promote
            fi
