version: 2
jobs:
  build-job:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Disconnect24/disguise-api
    steps:
      - checkout
      - run: 
          name: Install Google Cloud SDK
          comand: ./setup.sh
      # Download our go deps and test.
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  deploy-job:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Disconnect24/disguise-api
    steps:
      - run:
          name: Install Google Cloud SDK
          command: ./setup.sh
      - run:
          name: Deploy
          command: $HOME/google-cloud-sdk/bin/gcloud -q app deploy app.yaml --promote

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
