version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      # Download the Google Cloud SDK
      - run: curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
      - run: tar -C $HOME -vf /tmp/google-cloud-sdk.tar.gz
      - run: $HOME/google-cloud-sdk/install.sh
      # Set up client secret for GAE later on.
      - run: echo "$CLIENT_SECRET" | base64 --decode > ${HOME}/client-secret.json
      - run: $HOME/google-cloud-sdk/bin/gcloud --quiet components update app
      - run: $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file $(HOME)/client-secret.json
      - run: $HOME/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT

      # Download our go deps and test.
      - run: go get -v -t -d ./...
      - run: go test -v ./...
deployment:
  prod:
    branch: master
    commands:
      # And we're off!
      - gcloud -q app deploy app.yaml --promote --version=1
